name: Prepush CI

on:
  push:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: ['20.x']
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install PNPM
        run: npm i -g pnpm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: ESLint
        run: pnpm lint
      - name: Prettier write
        run: pnpm prettier:write
      - name: Prettier check
        run: pnpm prettier:check
      - name: Test
        run: pnpm test
